# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33db143dd19bc9d00394b4bb9d9bd913f047d1f02818f5a7e2e6f50284bde5070fa39176cbc3401ddb44d0a8152fb2bc71b9d81547a68ae138b54cad384dcbe5

test:
  secret_key_base: 619a03ff0b3713accdb5153bc7c5b199984550f9aab1766b2878c42494cbd7a33f300d387c81015b0256eb3494a06d8645cfcb3b7d862874c8d27310acac8c09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
